version: '3.8'

services:
  # 1. Cấu hình MySQL Server
  mysqldb:
    image: mysql:8.0
    container_name: tour_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=quanlybantour
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Correct path relative to the "tour" folder:
      - ./src/main/resources/create_sequences.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Cấu hình RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tour_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  db_data:cd